[assembly: System.Reflection.AssemblyVersion("5.3.0.0")]
[assembly: System.Reflection.AssemblyTitle("Alachisoft.NCache.OutputCache")]
[assembly: System.Reflection.AssemblyDescription("Output Cache Module 4.6.2")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("Alachisoft")]
[assembly: System.Reflection.AssemblyProduct("Alachisoft\x00ae NCache")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2005-2026 Alachisoft")]
[assembly: System.Reflection.AssemblyTrademark("NCache ™ is a registered trademark of Alachisoft.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("47ec45ba-2c3f-41ec-902a-18082401a37e")]
[assembly: System.Reflection.AssemblyFileVersion("5.3.6.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]